### ISSUE TITLE
AppStore Upload Issue - ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by chandreshpanchasara** [paytm/Paytm_Payments_iOS_Sample_Apps#2]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

https://github.com/paytm/Paytm_Payments_iOS_Sample_Apps/tree/master/ObjC

- We are getting above issue from Apple due to usage of UIWebView in libPaymentsSDK.a and PGTransactionViewController.h files. 

- Apple is not allowing *NEW apps to submit which are integrated with PAYTM iOS integration. 

- So there is no way to use current PAYTM SDK integration with iOS app for the AppStore.

- Please fix this issue in PAYTM code and use WKWebView instead of UIWebView in whole code of Objective C.

**Comment by chandreshpanchasara** [comment]
Hello guys,

This is really serious issue. Payment related features are on hold due to that. New app can not be submitted to Apple (They are quickly rejecting the upload) and they will discontinue support of older app too after December.

Please update UIWebView to WKWebView related scripts in the binary library.

**Comment by soumyavats** [comment]
Hi we have already made changes in swift PFB link -https://github.com/paytm/Paytm_Payments_iOS_Sample_Apps/tree/master/Swift/Swift%205

Objc framework is deprecated thats why we have not updated that and the updated framework is available in the swift 5 folder.

Please implement the framework available in the swift 5 folder.

**Comment by chandreshpanchasara** [comment]
Thank you.

It't working!
